-- ============================================================
-- Myystical_arts — Supabase Database & Storage Setup Schema
-- Run this in your Supabase Project SQL Editor (https://app.supabase.com)
-- ============================================================

-- 1. Create Categories table
CREATE TABLE IF NOT EXISTS public.categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,
    slug        TEXT NOT NULL UNIQUE,
    description TEXT DEFAULT '',
    sort_order  INTEGER DEFAULT 0,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create Actresses table
CREATE TABLE IF NOT EXISTS public.actresses (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    slug          TEXT NOT NULL UNIQUE,
    face_filename TEXT DEFAULT NULL,
    bio           TEXT DEFAULT '',
    instagram_url TEXT DEFAULT '',
    sort_order    INTEGER DEFAULT 0,
    is_active     INTEGER DEFAULT 1,
    created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Images table
CREATE TABLE IF NOT EXISTS public.images (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actress_id        BIGINT REFERENCES public.actresses(id) ON DELETE SET NULL,
    category_id       BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    filename          TEXT NOT NULL UNIQUE,
    original_filename TEXT NOT NULL,
    caption           TEXT DEFAULT '',
    width             INTEGER DEFAULT 0,
    height            INTEGER DEFAULT 0,
    file_size         BIGINT DEFAULT 0,
    sort_order        INTEGER DEFAULT 0,
    is_active         INTEGER DEFAULT 1,
    created_at        TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Create Revoked Tokens table
CREATE TABLE IF NOT EXISTS public.revoked_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti        TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create Settings table
CREATE TABLE IF NOT EXISTS public.settings (
    key        TEXT PRIMARY KEY,
    value      TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Default Categories
INSERT INTO public.categories (name, slug, description, sort_order)
VALUES
    ('Glamour',   'glamour',   'Red carpet & high fashion',         0),
    ('Candid',    'candid',    'Natural, behind-the-scenes moments', 1),
    ('Ethnic',    'ethnic',    'Traditional & ethnic wear',          2),
    ('Editorial', 'editorial', 'Magazine & editorial shoots',        3),
    ('Events',    'events',    'Award shows & public events',        4)
ON CONFLICT (name) DO NOTHING;

-- Seed Default Settings
INSERT INTO public.settings (key, value)
VALUES
    ('site_name',        'Myystical_arts'),
    ('site_tagline',     'Curated Indian Celebrity Gallery'),
    ('instagram_url',    'https://www.instagram.com/myystical__arts?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw=='),
    ('instagram_handle', '@myystical__arts')
ON CONFLICT (key) DO NOTHING;

-- Create Storage Bucket for Uploaded Photos
INSERT INTO storage.buckets (id, name, public)
VALUES ('gallery-uploads', 'gallery-uploads', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Public Read Policy
CREATE POLICY "Public Read Access"
ON storage.objects FOR SELECT
USING (bucket_id = 'gallery-uploads');

-- Storage Authenticated Insert/Delete Policy
CREATE POLICY "Admin Upload Policy"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'gallery-uploads');

CREATE POLICY "Admin Delete Policy"
ON storage.objects FOR DELETE
USING (bucket_id = 'gallery-uploads');
